// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY_aLVle9Mw6xnVejfsh0wk4izvIOtZFE',
    appId: '1:234939405246:web:d446359654ab5d61009fef',
    messagingSenderId: '234939405246',
    projectId: 'the-hoodz-7a518',
    authDomain: 'the-hoodz-7a518.firebaseapp.com',
    storageBucket: 'the-hoodz-7a518.firebasestorage.app',
    measurementId: 'G-K7H4C4FTXG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-1LyYQXjCAuXWJ2FAXcBY4aC8SSogyR0',
    appId: '1:234939405246:android:2f439e84c54c51e3009fef',
    messagingSenderId: '234939405246',
    projectId: 'the-hoodz-7a518',
    storageBucket: 'the-hoodz-7a518.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6jc1fUbXPHLCpyysz2txG5KpzyENzJXU',
    appId: '1:234939405246:ios:3386b645cc30ebde009fef',
    messagingSenderId: '234939405246',
    projectId: 'the-hoodz-7a518',
    storageBucket: 'the-hoodz-7a518.firebasestorage.app',
    iosBundleId: 'com.hoodz.user',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6jc1fUbXPHLCpyysz2txG5KpzyENzJXU',
    appId: '1:234939405246:ios:3386b645cc30ebde009fef',
    messagingSenderId: '234939405246',
    projectId: 'the-hoodz-7a518',
    storageBucket: 'the-hoodz-7a518.firebasestorage.app',
    iosBundleId: 'com.hoodz.user',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBY_aLVle9Mw6xnVejfsh0wk4izvIOtZFE',
    appId: '1:234939405246:web:ee1cfd0662a1d6e4009fef',
    messagingSenderId: '234939405246',
    projectId: 'the-hoodz-7a518',
    authDomain: 'the-hoodz-7a518.firebaseapp.com',
    storageBucket: 'the-hoodz-7a518.firebasestorage.app',
    measurementId: 'G-VTCHCTVFZX',
  );
}
